SimulateAlarm = false
Debug = false
ServiceURL = "127.0.0.1:5572"
RootURLPattern = "/blog-admin/"
StaticBlogDir = "blog-corsa"
VuetifyLibName = "vuetify.js"
VueLibName = "vue.js"
ServerName = "<todo in custom>"
PostSubDir = "posts"
PageSubDir = "pages"
AllowEmptyMail = false

[Relay]
SendMail = false
EmailTarget = "<todo in custom>"
MailFrom = "<todo in custom>"
Secret = "<todo in custom>"
Host = "<todo in custom>"
User = "<todo in custom>"

[Telegram]
SendTelegram = false
ChatID = -1
APIString = "<todo in custom>"

[Database]
DbFileName = "blog-corsa.db"
SQLDebug = false
ModerateCmt = true